variable "app_name" {}
variable "cidr_vpc" {}
variable "my_ip" {}
variable "public_key" {}
variable "game_instance_type" {}
variable "game_spot_price" {}
variable "bench_instance_type" {}
variable "bench_spot_price" {}
variable "subnet_name" {}
